### ISSUE TITLE
Disable zswap before using zram.

### ISSUE THREAD

**Issue by yutayu** [StuartIanNaylor/zram-swap-config#10]
https://wiki.archlinux.org/title/Zram
If the related [zswap](https://wiki.archlinux.org/title/Zswap) kernel feature remains enabled, it will prevent zram from being used effectively. This is because zswap functions as a swap cache in front of zram, intercepting and compressing evicted memory pages before they can reach zram. Despite the output of [zramctl(8)](https://man.archlinux.org/man/zramctl.8), most of zswap is unused in this circumstance. Therefore, it's recommended to permanently [disable zswap](https://wiki.archlinux.org/title/Zswap#Toggling_zswap) using the kernel parameter or sysfs setting before starting.

I didn't these.
How do you think to add disable zswap option on zram-swap-config?

**Comment by StuartIanNaylor** [comment]
If they have a kernel with Zswap enabled then its there problem and can use thr url you supplied.
