### ISSUE TITLE
Zram-config

### ISSUE THREAD

**Issue by StuartIanNaylor** [StuartIanNaylor/zram-swap-config#3]
If zram-swap-config interests you I suggest you look at zram-config it combines all features of log2zram, zram-dir & zram-swap-config into 1.

It uses a ztab where any number of swaps, zdir and a zlog can be defined and also uses OverlayFS so that much larger directories can be used without huge startup copies on start to volatile ram.

If zram-swap-config interests you and you wish features then shout away, but really its now defunct with zram-config offering much better methods in a variety of better ways.
https://github.com/StuartIanNaylor/zram-config

**Comment by Fungraphic** [comment]
Thank you for this info.
I installed zram-swap-config and zram-config.
I have a systemd [1] error: Failed to start zramdrive.
I will uninstall Zram-swap-config
: D

**Comment by StuartIanNaylor** [comment]
I haven't looked with pi and things for quite a while so maybe something with the Buster changes and updates.
I said I was going just to let these repos end if no one wants transfer.
Just started with another Pi4 playing with Arch Kodi & Chrome so I will have a look in the next couple of days.
Doubt it will be much as that is all it is a systemd script

**Comment by Fungraphic** [comment]
I installed your script on manjaro on SSD with 4GB of ram.
I uninstalled everything and reinstalled zram-config.
It works very well now.
I often promote your script because I find it excellent for small hardware configurations.

Here is an example.
https://www.manjaro.fr/forum/viewtopic.php?f=17&t=11650&p=126254#p126254

**Comment by StuartIanNaylor** [comment]
I would not say its excellent as it just started as a protest to the big distro's to drop what is the initial zram-config of debian and ubuntu that has circulated so much.
Its a terrible script that ignores other zram services and much of the new functionality and when I say new I mean the next release after first release of zram.

I have tried and complained to many and also stated that with zram you need to change the page striping to 0 as buffering with memory just causes latency.
Its not my script but zram is excellent if it is set up correctly and rather bemused that the old "divide by cores" script still exists.

**Comment by Fungraphic** [comment]
Little question:
Why not use LZ4HC?
Benchmark https://github.com/lz4/lz4

**Comment by StuartIanNaylor** [comment]
You can use any compression that is part of the kernel crypt selection.
Its very dependent on application and the new lzo-rle which is now default and best for swap in zram.
zram has different uses and for text compression zlib or zstd has much better compression rates.

Current defaults are just common with some common distro's such as Raspbian that lags behind others but if you have a kernel that supports lzo-rle and your use is swap then use it.

https://www.phoronix.com/forums/forum/software/mobile-linux/1086709-zram-will-see-greater-performance-on-linux-5-1-it-changed-its-default-compressor

**Comment by Fungraphic** [comment]
I uninstalled zram-config because it doesn't work properly on Manjaro.
Cannot have zram1 with / var / log
I reinstalled Zram-swap-config / tree / Swapiness-load-balancer.
After several tests ...
My config is for 4G RAM;
LZ4
30% ram
basic swapiness 80
vfs_cache_pressure 50

It seems fluid and efficient.

**Comment by yutayu** [comment]
@Fungraphic 
Mainly,Zram-config scripts is for pi and it needs apt.
then zram-swap-config is for another distro.
and Manjaro uses zramswap or systemd-swap.try it.

**Comment by StuartIanNaylor** [comment]
zram-swap-config & zram-config are different in configuration.
Both really to highlight to the many ultilities out there there is much more to zram than just swap.

Here issues are posted for zram-swap-config only.
zram-swap-config is a zram-swap utility systemd service only, zram-config is the diverse zram utility.
Both do check for existing zram usuage and will not overwrite and will co-exist.

I just got round to trying and it works fine on Arch Linux and Raspbian haven't got round to Ubuntu Eoan yet.
The new lzo-rle encryption is supposedly now the best and supperior for zram swap but zramctl just reports lzo prob due to the strings in zramctl have not yet been updated.
I didn't get rounf to googling a method to prove what crypt is loaded into zram so can not say for sure but if you have a newer kernel then its highly likely.
