### ISSUE TITLE
DRIVE_FACTOR config option is not very clear

### ISSUE THREAD

**Issue by EdoaLive** [StuartIanNaylor/zram-swap-config#4]
Hello,
Great project, but I think that DRIVE_FACTOR option is not clear.
I somewhat get what it does and it seems genius, but I don't get what the number stands for.
I think it deserves a better explanation.

**Comment by StuartIanNaylor** [comment]
I made an edit but if you want to offer a line I have no probs including.
Suggest you use https://github.com/StuartIanNaylor/zram-config instead though as zram-swap-config even if working and OK was just a shout out about the Ubuntu zram-conf.0.5 ignoring the kernel docs on various methods.
Zram-conf does zram-swap, zram-dir and a zram-log or the whole root zram in ephemeral mode.
Uses /etc/ztab to create a device for each line.
