### ISSUE TITLE
Optimizing swap on zram

### ISSUE THREAD

**Issue by yutayu** [StuartIanNaylor/zram-swap-config#9]
/etc/sysctl.d/99-vm-zram-parameters.conf

vm.swappiness = 180
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 125
vm.page-cluster = 0

Long time no see.
How is this custumasation?

**Comment by StuartIanNaylor** [comment]
If that workd for you then all good.
```
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 125
```
vm.watermark is ram not swap so not part of config

**Comment by yutayu** [comment]
ok Thanks.
